name: Build account-app
on:
  push:
    paths:
      - "apps/auth/**"
      - "*.gradle.kts"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run gradle build
        run: ./gradlew :apps:auth:build

      - uses: actions/upload-artifact@v2
        with:
          path: apps/auth/build/libs/*.jar